### ISSUE TITLE
Email client rendering issues in Outlook/Gmail App

### ISSUE THREAD

**Issue by jbauth0** [auth0/styleguide#101]
Rendering issues discovered in certain clients for the dark background email templates: 
1. MS Outlook →  inner white frame breaks at the bottom near the footer links (i.e. Terms of Service, etc.)
   http://d.pr/i/9WRq 
2. Gmail app (Android) → Footer font color displays as black on the dark background:
   http://d.pr/i/Vvqw 

Here's the code in Litmus: 
https://litmus.com/builder/documents/1064211/edit

**Comment by GMesyngier** [comment]
Hi @jbauth0, this issue is already fix in https://litmus.com/builder/documents/1064211/edit

**Comment by jbauth0** [comment]
Thanks @GMesyngier. Looking good in most clients but it looks like the Twitter footer image still looks horizontally misaligned. Is there anything you can do here? 
http://d.pr/i/1hKDc

**Comment by GMesyngier** [comment]
Sorry @jbauth0, the Twitter icon position is already fix in the same link. I was focusing in the other issues and I completly forgot about that. Thanks!
