### ISSUE TITLE
Extra space at the footer's bottom end

### ISSUE THREAD

**Issue by sanntu** [auth0/styleguide#12]
The Facebook's frame is generating an extra space at the footer's bottom end.

![image](https://cloud.githubusercontent.com/assets/1971729/10403360/58c24dd2-6ea1-11e5-9a9c-bc42e1016263.png)

![image](https://cloud.githubusercontent.com/assets/1971729/10403362/60c68124-6ea1-11e5-9768-820cf8fd24bb.png)

![image](https://cloud.githubusercontent.com/assets/1971729/10403371/72c34146-6ea1-11e5-9c7a-800f8f4d296a.png)

**Comment by vctrfrnndz** [comment]
No repro.
