### ISSUE TITLE
licensing?

### ISSUE THREAD

**Issue by elioqoshi** [auth0/styleguide#198]
The licensing situation is a bit confusing:
https://github.com/auth0/styleguide/pull/19

The style guide itself invites viewers to "Fork from GitHub" while the licensing does not allow doing anything with the code in the repo (even non branding related). Could you clarify please? The style guide is a great reading resource and I'd like to know whether I can recommend others to have a look at it

**Comment by elioqoshi** [comment]
@francocorreasosa could you clarify this?

**Comment by francocorreasosa** [comment]
Hey @elioqoshi, you may want to check https://github.com/auth0/cosmos which is licensed MIT :)

**Comment by elioqoshi** [comment]
@francocorreasosa thanks!
