### ISSUE TITLE
[bug] dropdown with long text on the right nav bar breaks

### ISSUE THREAD

**Issue by solepano** [auth0/styleguide#31]
Width should increase as content length increases:

<img width="1019" alt="dropdown" src="https://cloud.githubusercontent.com/assets/1350396/14532936/52548ab0-0239-11e6-882c-d8403c2f3327.png">

**Comment by vctrfrnndz** [comment]
Thanks. I will make the width bigger. But ultimately we want to have a max-width for these kind of element. For that case I will add a `.truncate` class that will automatically collapse long texts with `...`

**Comment by solepano** [comment]
Could this be fixed today? I migrated to new styleguide in the last support center version which is going to be shipped tomorrow. I need this fix to be included... thanks!

**Comment by vctrfrnndz** [comment]
@solepano Yes, I will release a new version before in an hour or so with this fix

**Comment by vctrfrnndz** [comment]
@solepano Fixed in `4.4.4`. Please use `.dropdown-menu-md` or `dropdown-menu-lg` modifier classes. And add `.text-truncate` for very large texts that need to be collapsed 🤔.
