### ISSUE TITLE
Add tables to styleguide.auth0.com and fix their styles

### ISSUE THREAD

**Issue by solepano** [auth0/styleguide#32]
Tables look weird. Table headers have double border (one from the `th` another from the first row `tds`). Also header text is too thick.
<img width="1116" alt="ticketstable" src="https://cloud.githubusercontent.com/assets/1350396/14568513/b8f3771e-030f-11e6-9b80-4afc7ac22a2d.png">

**Comment by vctrfrnndz** [comment]
FIxed on 4.4.9 :100:

**Comment by vctrfrnndz** [comment]
@solepano https://styleguide.auth0.com/#tables 🚀
