### ISSUE TITLE
Code picker UI

### ISSUE THREAD

**Issue by ntotten** [auth0/styleguide#36]
I need UI for a code picker like what is used on this page: https://auth0.com/docs/server-apis/hapi#4-call-your-api

You can see another implementation here: https://apiembed.com/

The idea of this component is that it will allow users to pick which language they want to see a particular code example in.

Mockup:

![image](https://cloud.githubusercontent.com/assets/282782/14576223/257903ca-031c-11e6-874b-608696f954c4.png)

**Comment by woloski** [comment]
and it needs a copy to clipboard button

**Comment by vctrfrnndz** [comment]
This is my proposed design for this component, let me know your toughts

![image](https://cloud.githubusercontent.com/assets/3391028/14607383/aff64f8e-0557-11e6-9286-e54bbcbd8f34.png)

cc @rickyrauch

**Comment by vctrfrnndz** [comment]
This is available in 4.6.1 😍
