### ISSUE TITLE
Can we use this StyleGuid for our website (Not related to Auth0)

### ISSUE THREAD

**Issue by ricardopolo** [auth0/styleguide#37]
Thanks!

**Comment by rickyrauch** [comment]
@ricardopolo 

Hi Ricardo, 

Currently, Styleguide is only available for the development of <a href="https://manage.auth0.com">extensions</a>. We'll update the terms very soon.

Thanks for your interest.

**Comment by ricardopolo** [comment]
@rickyrauch thanks. But it will update to be usable outside?

I mean, can I start development a website with this styleguide and wait to the terms upated? (or will lost the work).

Regards!

**Comment by rickyrauch** [comment]
Our current licence says "This is for internal use by Auth0 only.". **Today this is intellectual property of Auth0.**

What we are going to allow is to make <a href="https://manage.auth0.com/">Extentions</a> using Styleguide.

Thanks.

**Comment by ricardopolo** [comment]
Thanks!
