### ISSUE TITLE
Update new labels design

### ISSUE THREAD

**Issue by yohannaje** [auth0/styleguide#67]
They already appear on the styleguide.sketch.

![screen shot 2016-06-07 at 7 11 57 pm](https://cloud.githubusercontent.com/assets/829179/15970451/02318fc0-2f0b-11e6-904f-f61fa0a4e6cc.png)

Thanks!

**Comment by arielger** [comment]
Added in version 0.0.3 of new styleguide v5 components css bundle 👍
