### ISSUE TITLE
home icon in breadcrumb is not loaded when using .has-homepage modifier

### ISSUE THREAD

**Issue by solepano** [auth0/styleguide#68]
https://cdn.auth0.com/lib/breadcrumb/img/home-icon-dark.svg throws 403 error

**Comment by vctrfrnndz** [comment]
Thanks. Correct path would be https://cdn.auth0.com/styleguide/latest/lib/breadcrumb/img/home-icon-dark.svg

**Comment by vctrfrnndz** [comment]
This fixed in the latest version.
