### ISSUE TITLE
Set icons for new docs

### ISSUE THREAD

**Issue by mpaktiti** [auth0/styleguide#69]
We have 2 new Java docs on our website https://auth0.com/docs/quickstart/webapp/
- [Java Spring MVC](https://auth0.com/docs/server-platforms/java-spring-mvc)
- [Java Spring Security MVC](https://auth0.com/docs/server-platforms/java-spring-security-mvc)

These 2 new docs should use the same icon as [Java Spring Security API](https://auth0.com/docs/server-apis/java-spring-security).

Docs missing the icon:
![image](https://cloud.githubusercontent.com/assets/11715799/16230832/1b3e5326-37cc-11e6-8725-f49dc0b9df70.png)

Icon to be used:
![image](https://cloud.githubusercontent.com/assets/11715799/16230900/5e25874a-37cc-11e6-9b52-7d1fbcef79da.png)

**Comment by vctrfrnndz** [comment]
Added wildcards. Will be fixed once styleguide is updated in the corresponding projects. (Docs and Manage)
