### ISSUE TITLE
Add home links cards to styleguide, used in new docs and new support center

### ISSUE THREAD

**Issue by solepano** [auth0/styleguide#70]
There is a new design for docs home links which is also shared with new support center:

![5](https://cloud.githubusercontent.com/assets/1350396/16244972/0a65c972-37d5-11e6-859b-d9febcf3962a.png)

@nkohari has started the implementation on his doc's fork: https://github.com/nkohari/auth0-docs/blob/new-navigation/client/styles/inc/category-card.styl, but since same styles are needed in the support center this should be moved to the styleguide.

Thanks,
Sole

**Comment by vctrfrnndz** [comment]
Added in 4.7.6
