### ISSUE TITLE
Improve footer 

### ISSUE THREAD

**Issue by yohannaje** [auth0/styleguide#83]
Footer's design is a bit messy and confusing, you cant tell what the phone numbers are about, they have different weights and support title is a bit (???) on the bottom.

![screen shot 2016-07-12 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/829179/16812957/d17f4a24-4905-11e6-8f06-c6642bef0475.png)
![screen shot 2016-07-11 at 5 29 45 pm](https://cloud.githubusercontent.com/assets/829179/16813215/f5135470-4906-11e6-822f-fba9625581e6.png)

**Comment by vctrfrnndz** [comment]
This is serviced by: https://github.com/auth0/styleguide/pull/96
