### ISSUE TITLE
Feature: Language/Version Selector

### ISSUE THREAD

**Issue by chenkie** [auth0/styleguide#85]
We currently have a language selector that is used in at least one place: https://auth0.com/docs/connections/passwordless/ios-touch-id-objc

The code for it is here: https://github.com/auth0/docs/blob/master/articles/connections/passwordless/_ios-language-picker.md

We should refresh the design on this before making it into a more general purpose and configurable selector as we want to start using it in more docs :)

**Comment by vctrfrnndz** [comment]
👍

**Comment by arielger** [comment]
We can use the `<Select>` component from the auth0 react-styleguide (http://styleguide.auth0.com/#/react/select) as we are doing with the Version selector (https://auth0.com/docs/libraries/lock/v10).

I will start working on a solution to Language selection in docs ;)
