### ISSUE TITLE
Add Android Phone Mockup

### ISSUE THREAD

**Issue by ntotten** [auth0/styleguide#87]
Currently we have an iPhone mockup. For docs we also need an android mockup. http://styleguide.auth0.com/#phone-mockup

**Comment by vctrfrnndz** [comment]
Hi, @ntotten this is meant to be a generic phone for all our mobile screenshots. Maybe we can look at making it even more generic (?)

**Comment by arielger** [comment]
We have made the phone more generic removing the home button from the phone design (version 4.8.8).
