### ISSUE TITLE
Create component for Quickstarts

### ISSUE THREAD

**Issue by yohannaje** [auth0/styleguide#91]
We've had a request on this as some parts of the boxes break on mobile screens.
the two buttons in the seed downloader need margins, and the text in the sign up box needs to be centered.

<img width="1128" alt="screen shot 2016-08-18 at 5 01 33 pm" src="https://cloud.githubusercontent.com/assets/829179/17788725/72f950cc-6565-11e6-9516-998804c23392.png">

<img width="735" alt="screen shot 2016-08-18 at 5 04 34 pm" src="https://cloud.githubusercontent.com/assets/829179/17788834/e0835d04-6565-11e6-8de7-1436f85c3d93.png">

**Comment by vctrfrnndz** [comment]
👍 Sounds like a plan. We'll add this in the next release

**Comment by mpaktiti** [comment]
Hey, just wanted to let you know that this happens on laptops also, if you go to the quickstart from the dashboard: Dashboard > Clients > select a client > Quickstart > select a quickstart:

![image](https://cloud.githubusercontent.com/assets/11715799/17825651/c2af5cd8-661e-11e6-8777-8152b9b873ba.png)

If I go to the same quickstart using the navigation from [docs](https://auth0.com/docs) the buttons are ok.

**Comment by arielger** [comment]
Fixed in this commit: 
https://github.com/auth0/auth0-docs/commit/eb69d09819bd686a426294a6e5cf05211a644004
