### ISSUE TITLE
Templates for Email Redesign

### ISSUE THREAD

**Issue by jbauth** [auth0/styleguide#97]
## Notes / requests:
- support@auth0.com is no longer public facing and ask.auth0.com has been deprecated. 
- Review in Litmus

**Comment by jbauth0** [comment]
https://docs.google.com/a/auth10.com/document/d/11vQSKAAcnofnqLrTTrsAK6R3HUgu51lUj0VUQTju4Vg/edit?usp=sharing

**Comment by jbauth0** [comment]
the grey body text is hard to read on mobile. please darken and enlarge the text to increase readability on mobile. 
![slack for ios upload](https://cloud.githubusercontent.com/assets/16821698/19007051/b1c766e4-8717-11e6-994e-449972295d91.jpg)
